### ISSUE TITLE
[JP] 1st line of street address is never set for japanese address

### ISSUE THREAD

**Issue by vincent-wantomo** [amzn/amazon-payments-magento-2-plugin#233]
#### What I expected

During checkout, first street address is set correctly

#### What happened instead

During checkout, first street address is never set and Magento triggers an error.

#### Steps to reproduce the issue

I identified the "issue" (it's either intended or a mistake) but I wanted more explanation if possible.

The error occur from this file : 

> amzn/amazon-pay-and-login-magento-2-module/src/Core/Domain/AmazonAddressDecoratorJp.php

line 46 to 51
> if (empty($city)) {
>             $lines[] = trim($line1 . ' ' . $line2);
>         } else {
>             $lines[] = $line2;
>         }
>         $lines[] = $line3;
> 

If there's no city (which is unlikely to happen), $line1 (of address) is skipped. Why ? It would always result an error during checkout because "street" is empty. More other, if you use the default address for a japanese customer test account, there's a first line for the address (ex : 1-17-25 Shinkamata).

> JP APA test test1
1-17-25 Shinkamata
Ota-ku, Tokyo 144-8588
Japan
電話番号： 09056412829

I know the logic for japanese address can be sometimes quite different than usual (for the frontend), but first line of street address should never be skipped, it's unconventional. 

#### Your setup

* Magento version: 2.2.4
* Magento Edition: Community
* Country : JP

Thank you !

**Comment by vincent-wantomo** [comment]
After some testing on a live amazon environment, it would appear that REAL japanese addresses don't have a field "city", unlike the default test account on the sandbox environment. However, this triggers another error, please see below.

**On a Live version**

"City" field is not set in the result of the API (GetOrderReferenceDetailsResponse)

file : amzn/amazon-pay-and-login-magento-2-module/src/Payment/Model/AddressManagement.php
line 113 : getShippingAddress
line 121 : $shippingAddress = $data['OrderReferenceDetails']['Destination']['PhysicalDestination']

Exemple : 

>     [StateOrRegion] => 東京都
>     [Phone] => xxxxx
>     [CountryCode] => xx
>     [PostalCode] => 135-0043
>     [Name] => xxxx
>     [AddressLine1] => xxxxx
>     [AddressLine2] => xxxxx

_Note : I removed some confidential data._
_Side note : AddressLine1, in japan, usually corresponds to city + street address._

And will trigger an error later because this field is not set inside the array : 

line 176 : convertToMagentoAddress
line 178 : $amazonAddress  = $this->amazonAddressFactory->create(['address' => $address]);
file : amzn/amazon-pay-and-login-magento-2-module/src/Core/Domain/AmazonAddressFactory.php
line 76 : AmazonAddressInterface::CITY => $address['City']

$address['City'] is never set. I tried on 3 different japanese addresses. If we add controls over this field, then the issue reported will not be triggered because of : 

file : src/vendor/amzn/amazon-pay-and-login-magento-2-module/src/Core/Domain/AmazonAddressDecoratorJp.php
line 38 : getLines
line 46 : 

```
if (empty($city)) {
            $lines[] = trim($line1 . ' ' . $line2);
        } else {
            $lines[] = $line2;
        }
```
In this case, we indeed never have $city so $line1 is always set (but I still think it's little bit weird to have only $line2 in the else statement. Maybe it should be $city + $line2).

**Conclusion**

1) In my opinion, either the API should send us an empty "city" field or we need more control on this field. I don't know which solution is the cleanest/match the most with the other countries.

2) Also, please try to use a most closest live environment address for the default test account since we don't have city address in Japan.

3) Fix the if/else statement under the getLines()

I know this kind of localization issues are difficult to take care of and you are already doing a great job, so if I can help you by bringing more information, let me know.

**Comment by lemked** [comment]
Hi @vincent-wantomo ,

Thank you for your detailed explanations. We can confirm this issue and will analyze this internally. I will provide an update here as soon as possible.

Kind regards,
Daniel

**Comment by lemked** [comment]
Related to issue #267

**Comment by lemked** [comment]
Fixed in master and 2.x branch. Will be closed once we have released a new version.

**Comment by lemked** [comment]
Fixed with version 3.1.4 that is included in Magento 2.3.1. Also fixed in Magento 2.2.8.

Closing issue. Please re-open if still facing this issue.

**Comment by vincent-wantomo** [comment]
Hello,

I'm reopening this issue since it's still happening with the new version. Again, it's working perfectly with test account, but almost never working with REAL Japanese addresses.

Would it be possible for Amazon to let us create our own test address ? It seems like it's limited to only firstname/lastname. Japanese addresses have their own standards. Almost all of them doesn't have "city" field. I'm tired of using real Amazon account to debug this kind of localization issues.

The error is triggered because 1st line of street is used for city ($this->amazonAddress->getCity() ?? $this->amazonAddress->getLine(1)), but then, it's removed form the array (this->amazonAddress->getLines()), which becomes empty if there's only one line of street address.

vendor/amzn/amazon-pay-and-login-with-amazon-core-module/Domain/AmazonAddressDecoratorJp.php::getLines
```
/*
* AmazonAddressDecoratorJp->getCity() returns address line 1 when city is empty.
* Omit line 1 from the street address in this case.
*/
return array_slice($this->amazonAddress->getLines(), empty($city) ? 1 : 0);
```
It's even written in the comment. Line 1 will be excluded from array.

So...

vendor/amzn/amazon-pay-module/Helper/Address.php::convertToMagentoEntity
`$address->setStreet(array_values($lines));
`
$lines will be an empty array if there's only one street address with no city.

I don't know what would be a nice fix because Magento will not allow an empty street, unless we bypass the validation or use a japanese space character (which is not really nice but will bypass the validation).

**Comment by lemked** [comment]
Thanks for the feedback @vincent-wantomo . We will verify this with our Japanese team and get back to you.

Kind regards,
Daniel

**Comment by christianzichichi** [comment]
Hi @vincent-wantomo ,
sorry for the delay here. The issue with JP address parsing and validation has been solved with release 3.5.1 of our extension, you can find patch instructions available for Magento 2.3.x branch [here](https://github.com/amzn/amazon-payments-magento-2-plugin/blob/3.4.x/PATCH_INSTRUCTIONS.MD)

Thanks
Regards

Christian
