### ISSUE TITLE
Klarna Checkout Extension & Amazon Payments

### ISSUE THREAD

**Issue by zsco** [amzn/amazon-payments-magento-2-plugin#286]
Sorry for opening a new issue. I was not sure if I was supposed to comment in the already existing issue with the same problem which, unfortunately, is already closed. 

As it happens we also want to use Klarna Checkout extension together with the Amazon Payment Extension. So once i activate the klarna checkout, I have to register amazon payment with klarna checkout as described in their integration documentation  (https://marketplace.magento.com/media/catalog/product/klarna-m2-checkout-4-2-1-ee/user_guides.pdf).

To invoke the external payment method, the klarna extension requires a redirect url, which actually "starts" the external payment process. For example, with paypal one would use "WEBSITE_URL/paypal/express/start". 

My question/issue is: Is there an actual redirect url, the amazon extension provides, which would be appropriate? The only route i found was the ipn one, which, obviously, is not what I want.

Thank you

#### 

* Magento version: 2.2.4
* Amazon Pay Extension Version: 2.0.12
* Magento Edition: Community

**Comment by lemked** [comment]
Hi @zsco ,

Thanks for raising this. Can you provide us the issue ID that you are referring to, that has already been closed?

Kind regards,
Daniel

**Comment by zsco** [comment]
Yes, of course, it's #247, https://github.com/amzn/amazon-payments-magento-2-plugin/issues/247

regards

**Comment by lemked** [comment]
A fix for this issue has been provided in https://github.com/amzn/amazon-payments-magento-2-plugin/pull/401. 

Implemented behavior: If a customer logs in with Amazon (using an Amazon Pay or Login with Amazon button), the customer will be redirected to the Amazon Pay checkout. If the customer clicks the Checkout button instead, he will be redirected to the Klarna Checkout.

Please note that once logged in with Amazon, the customer will always be redirected to the Amazon Pay checkout. Customers can however jump back to the Klarna Checkout by clicking the "Return to standard checkout" link in the Amazon Pay checkout.

Leaving issue open until the fix has been published in the next version of the extension.

**Comment by zsco** [comment]
Sounds wonderful, thank you!

**Comment by TonyRutherford1** [comment]
@lemked We are having this issue as well when we add amazon Pay to Klarna Checkout. We do not have a redirect URL to add in for amazon pay.

**Comment by lemked** [comment]
Dear @TonyRutherford1 ,

Yes, this has been fixed in version 3.1.4 of our extension (bundled with Magento 2.3.1). If you're using a version on the 2.2 branch of Magento 2, the patches could potentially be applied manually (see related pull request #401).

Kind regards,
Daniel

**Comment by TonyRutherford1** [comment]
Hi @lemked Thank you for the reply. We are running Magento 2.3.1 using the bundled version. But are still facing the issue

**Comment by lemked** [comment]
Hi @TonyRutherford1 ,

Can you provide a URL where this can be reproduced? Alternatively, a few screen shots or a screen recording. I would like to make sure this is the same issue before further investigating.

Kind regards,
Daniel
