### ISSUE TITLE
Mini-cart keep the old items after placing order successfully. Local Storage isn't cleared

### ISSUE THREAD

**Issue by vincent-le89** [amzn/amazon-payments-magento-2-plugin#630]
I am seeing an issue when placing an order using amazon pay2 , when I have placed the order and returned to the site the mini basket is still showing that I have 1 item in my mini-cart.
When I go to cart page or checkout page, mini-cart is refreshed and no-item is shown.
#### What I expected

Local Storage should be updated after place order successfully
#### What happened instead
Local Storage isn't updated.

So mini-cart still show the old items which placed an order successfully
#### Steps to reproduce the issue
1. Configure Amazon Pay in admin:
![image](https://user-images.githubusercontent.com/49143689/79317153-8896dc00-7f2f-11ea-8390-5245bb0bac1e.png)

2. Add item to Cart and place an order with the payment method "Amazon pay2"
3. Place order
4. Come back from Amazon Pay2, mini-cart keep the old items 

#### Your setup

* Magento version: 2.3.4
* Amazon Pay Extension Version: 
* Magento Edition: Enterprise / Enterprise Cloud
* Shop URL : https://mcstaging.bbclothing.co.uk/

**Comment by christianzichichi** [comment]
Hi @vincent-le89 , thanks for contacting us. This graphic bug  has been solved in the latest release of our module, please use these instructions to upgrade plugin version. 
https://gist.github.com/christianzichichi/79831e03451e17c491fb8cd7dc20b6f8

Thanks
Regards
Christian

**Comment by vincent-le89** [comment]
Hi @christianzichichi  and guys

I followed up your instruction but seem it doesn't resolve our issue. Refer my record: https://youtu.be/gJwPrUlGpk0
![image](https://user-images.githubusercontent.com/49143689/79527662-62d61800-8092-11ea-84ce-64617780e38b.png)

Amazon doesn't clear the old item.
Besides, there is another error after upgrading lib. It happened when I tried to place an order after placing an order successfully again. I turned on the developer tool in chrome.
![image](https://user-images.githubusercontent.com/49143689/79527612-4043ff00-8092-11ea-987b-ee3f2f86ae26.png)
Please advise how we can resolve it thoroughly
Let me know if you need any information.
Thanks.

**Comment by christianzichichi** [comment]
Hi @vincent-le89,
I apologize I did not realize the first time you were referring to the V2Checkout plugin. The changes to solve that issue are currently under review here https://github.com/amzn/amazon-payments-magento-2-plugin/pull/636 
I will report back here once that PR is merged. 

Thanks
Regards

Christian

**Comment by christianzichichi** [comment]
Hi @vincent-le89 ,
the PR has been merged. Please install the latest version of the plugin following these instructions to solve your issue: composer require amzn/amazon-payments-magento-2-plugin:dev-V2checkout-1.2.x
https://github.com/amzn/amazon-payments-magento-2-plugin/blob/V2checkout-1.2.x/README.md#composer-installation

thanks! 
Regards

Christian

**Comment by vincent-le89** [comment]
Hi @christianzichichi 

Sorry for replying late.
I just tested Amazon Pay with theme **luma** on our staging. Seem the new version causes a new error: We can't continue to complete the order at step 2 after coming back from the Amazon side. Refer my record: https://drive.google.com/file/d/1Nz-3fRo3YHZcZgvKVa0_qvzutZ-INc04/view
There isn't any button to complete the checkout steps.
Please advise what I should handle this issue. Thanks

**Comment by vincent-le89** [comment]
Hi @christianzichichi 
Do you have any update on this ticket? Thanks
Looking forward to hearing your response.

**Comment by christianzichichi** [comment]
Hi @vincent-le89 , 
our agency is already looking into this issue and a support request has already been created. Please contact us at payments-cp-devel@amazon.com and we'll loop you in into the request.

Thanks
Regards
Christian
